### ISSUE TITLE
Is it possible to prove this simple fact on List.join?

### ISSUE THREAD

**Issue by safinaskar** [JLimperg/aesop#8]
Hi. Consider this theorem:
```lean
theorem elem_join (aty : Type) (a : aty) (xs : _) : (List.elem a (List.join xs) -> exists z, List.elem a z && List.elem z xs) := by sorry
```
Is this possible to prove it with aesop? I tried to write `by aesop` in the end and failed

**Comment by JLimperg** [comment]
Hey! This is expected for two reasons:

- Aesop doesn't do induction and probably never will. This is because induction is hard and expensive to automate, so in an interactive prover, I don't think it's worth it. I'm currently writing a new version of the README that covers this point.
- Existential targets require metavariables, which are currently not well-supported. This is something I've been working on a lot and I think I have a good solution, but it's not implemented yet.

In general, the builtin rules are not properly fleshed out yet (e.g. for negation, existentials, `And`, `Or`, basic data types), so I wouldn't expect Aesop to prove many goals without any help. I hope that'll change soonish.

**Comment by safinaskar** [comment]
Ok, thanks a lot

**Comment by JLimperg** [comment]
Sure! I'll close the issue for now since this particular lemma won't be supported any time soon. Thanks for trying out the tactic!
